apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # NB : on inclut /prometheus parce que le serveur tourne avec
    # --web.route-prefix=/prometheus (pour être servi sous /prometheus/ via Nginx).
    url: http://prometheus:9090/prometheus
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
